- name: install aptitude
  apt: pkg=aptitude state=latest
  become: true

- name: update package list & upgrade existing packages
  apt: update_cache=yes upgrade=yes cache_valid_time=3600
  sudo: yes

- name: install common packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - git
    - logrotate
    - ntp
    - python-pycurl
    - supervisor
    - unattended-upgrades
    - vim
